//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBank.Aplicacion.ServiceDigitalBank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalBank.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDigitalBank.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListUsuario", ReplyAction="http://tempuri.org/IService1/ListUsuarioResponse")]
        DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO[] ListUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListUsuario", ReplyAction="http://tempuri.org/IService1/ListUsuarioResponse")]
        System.Threading.Tasks.Task<DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO[]> ListUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUsuario", ReplyAction="http://tempuri.org/IService1/InsertUsuarioResponse")]
        int InsertUsuario(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUsuario", ReplyAction="http://tempuri.org/IService1/InsertUsuarioResponse")]
        System.Threading.Tasks.Task<int> InsertUsuarioAsync(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUsuario", ReplyAction="http://tempuri.org/IService1/UpdateUsuarioResponse")]
        int UpdateUsuario(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUsuario", ReplyAction="http://tempuri.org/IService1/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<int> UpdateUsuarioAsync(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUsuario", ReplyAction="http://tempuri.org/IService1/DeleteUsuarioResponse")]
        int DeleteUsuario(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUsuario", ReplyAction="http://tempuri.org/IService1/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task<int> DeleteUsuarioAsync(int IdUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DigitalBank.Aplicacion.ServiceDigitalBank.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DigitalBank.Aplicacion.ServiceDigitalBank.IService1>, DigitalBank.Aplicacion.ServiceDigitalBank.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO[] ListUsuario() {
            return base.Channel.ListUsuario();
        }
        
        public System.Threading.Tasks.Task<DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO[]> ListUsuarioAsync() {
            return base.Channel.ListUsuarioAsync();
        }
        
        public int InsertUsuario(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO) {
            return base.Channel.InsertUsuario(usuarioDTO);
        }
        
        public System.Threading.Tasks.Task<int> InsertUsuarioAsync(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO) {
            return base.Channel.InsertUsuarioAsync(usuarioDTO);
        }
        
        public int UpdateUsuario(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO) {
            return base.Channel.UpdateUsuario(usuarioDTO);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUsuarioAsync(DigitalBank.Aplicacion.ServiceDigitalBank.UsuarioDTO usuarioDTO) {
            return base.Channel.UpdateUsuarioAsync(usuarioDTO);
        }
        
        public int DeleteUsuario(int IdUsuario) {
            return base.Channel.DeleteUsuario(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUsuarioAsync(int IdUsuario) {
            return base.Channel.DeleteUsuarioAsync(IdUsuario);
        }
    }
}
